<a href="https://colab.research.google.com/github/mkane968/digital-text-methods/blob/main/Tutorial_1_Intro_to_Text_Analysis_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Tutorial 1: Introduction to Text Analysis in Python

### Learning Goals

By the end of this tutorial, you should be able to:

Run code in Google Colab.

*   Recognize basic Python objects such as strings, lists, and numbers.
*   Store information in variables.
*   Create and inspect a pandas DataFrame.
*   Perform a few basic operations on textual data.
*   Understand how these concepts will eventually allow us to work with a corpus.

This tutorial draws from the following resources:
- [NLTK: *Natural Language Processing with Python*](https://www.nltk.org/book/) — Bird, Steven, Ewan Klein, and Edward Loper. *Natural Language Processing with Python*. O'Reilly Media, 2009.
- [Text Analysis for Humanities Research](https://github.com/alexbrandsen/Text-Analysis-for-Humanities-research) — Introductory Python and text-analysis notebooks designed for humanities researchers.
- [pandas: Getting Started Tutorials](https://pandas.pydata.org/docs/getting_started/intro_tutorials/index.html) — Official tutorials for working with DataFrames and tabular data in Python.
- [Python for Everybody](https://www.py4e.com/) — Charles Severance's introductory Python materials for beginning programmers.

### But First: What is Google Colab?

Google Colab is a notebook environment that allows us to write and run Python code in a web browser.

A notebook consists primarily of two kinds of cells:

*   Text cells contain explanations, instructions, headings, links, etc.

*   Code cells contain Python code that the computer can execute.

You do not need to install Python on your computer to use Colab.

### 1. Running Your First Cell

Click on the code cell below. Then click the Play (▶) button on the left side of the cell.

You can also run a cell using `Shift + Enter`

In [21]:
print("Hello, world!")

Hello, world!

The text that appears underneath the cell is the output.

Try changing "Hello, world!" to another message and run the cell again.

### 2. Working with Text Data
Because we are interested in text analysis, most of the data we work with will consist of **language**: words, sentences, paragraphs, poems, novels, interviews, and other texts.

Python calls a piece of textual data a `string`.

To tell Python that something is a string, we place it inside quotation marks: `"Hello, world!"`

Compare these two cells:

In [22]:
Frankenstein

NameError: name 'Frankenstein' is not defined

In [51]:
"Frankenstein"

'Frankenstein'

The first works because Python recognizes "Frankenstein" as text.

The second will produce an error because Python assumes Frankenstein is the name of something we've already defined, but it is not.

###3. Saving Text as a Variable

Rather than typing the same text repeatedly, we can save it as a variable.

A variable is a name that we assign to a piece of data.

In [49]:
title = "Frankenstein"

title

'Frankenstein'

Python remembers that the variable title contains the string "Frankenstein".

We can create other variables:

In [50]:
author = "Mary Shelley"

opening = "You will rejoice to hear that no disaster has accompanied the commencement of an enterprise which you have regarded with such evil forebodings."

Try displaying each one:

In [47]:
author

'Mary Shelley'

In [48]:
opening

'You will rejoice to hear that no disaster has accompanied the commencement of an enterprise which you have regarded with such evil forebodings.'

###4. Working with Strings

Once Python recognizes something as a string, we can perform operations on it.

These operations are called methods. Methods can` be applied to data stored in a variable using the format `variable.method()

Let's create a short piece of text and store it in the variable `text`:

In [23]:
text = "It Was A Dark and Stormy Night."

Now let's apply the method lower(), which lowercases each word in the string.

In [24]:
text.lower()

'it was a dark and stormy night.'

However, if you run the variable, it is still the original version.

In [25]:
text

'It Was A Dark and Stormy Night.'

If we want to save the transformed text, we can assign it to a variable:

In [26]:
lowercase_text = text.lower()

lowercase_text

'it was a dark and stormy night.'

Other methods that can be performed include:
* `.upper()` — converts all text to uppercase
* `.title()` — capitalizes the first letter of each word
* `.strip()` — removes extra spaces from the beginning and end of a string
* `.replace()` — replaces one piece of text with another
* `.split()` — splits a string into a list of words
* `.count()` — counts how many times a string occurs
* `.startswith()` — checks whether a string begins with specified text
* `.endswith()` — checks whether a string ends with specified text

###5. From a String to Word Lists

So far, Python sees our sentence as one string. But text analysis often requires us to work with individual words.

One simple method is `.split():`

In [27]:
text.split()

['It', 'Was', 'A', 'Dark', 'and', 'Stormy', 'Night.']

Let's save the result:

In [28]:
words = text.split()

A string stores text as one piece of data. But what did .split() create?

['It', 'was', 'a', 'dark', 'and', 'stormy', 'night.']

This is called a **list**. A list allows us to store multiple pieces of data together. Lists are surrounded by square brackets [ ], with individual items separated by commas.

We can also create a list ourselves and store it in a variable:

In [29]:
words = ["It", "was", "a", "dark", "and", "stormy", "night"]

We can use the len() function to get the length of a list. For text analysis, this gives us a very simple way to count the number of words in a text.

In [30]:
len(words)

7

Len() also works for strings-but it counts characters, not words.

In [31]:
len(text)

31

We can also retrieve individual items from a list using their position, called an index.

One unusual feature of Python is that counting begins at 0:


```
words[0]   # first word
words[1]   # second word
words[2]   # third word
```

In [32]:
words[0]

'It'

Try retrieving the word "dark" from the list.

In [33]:
words[3]

'dark'

We can also retrieve several items at once. This is called slicing a list.

In [34]:
words[0:4]

['It', 'was', 'a', 'dark']

Turning a string into a list gives us much more control over the individual words in a text.

For example:

In [35]:
text = "It was a dark and stormy night."
words = text.lower().split()

len(words)

7

We have now performed several steps:

**original text → lowercase text → list of words → word count**

This is a very simple example of text preprocessing: transforming raw text into a form that we can analyze computationally.

###6. Counting Words with Counter

Now that we have turned our text into a list of words, we can begin to ask questions about how frequently different words occur.

Python has a useful tool called `Counter` that counts how many times each item appears in a list.

First, we need to import `Counter`:

In [36]:
from collections import Counter

Python includes many useful tools that are not loaded automatically. The import command makes one of those tools available for us to use.

Now let's create a slightly longer piece of text:

In [37]:
text = """
The night was dark and quiet.
The night was cold.
The night was very dark.
"""

As before, we can convert our text to lowercase and split it into a list of words:

In [38]:
words = text.lower().split()

words

['the',
 'night',
 'was',
 'dark',
 'and',
 'quiet.',
 'the',
 'night',
 'was',
 'cold.',
 'the',
 'night',
 'was',
 'very',
 'dark.']

Now we can use Counter on our list:

In [39]:
word_counts = Counter(words)

word_counts

Counter({'the': 3,
         'night': 3,
         'was': 3,
         'dark': 1,
         'and': 1,
         'quiet.': 1,
         'cold.': 1,
         'very': 1,
         'dark.': 1})

We can use the .most_common() method to arrange our words by frequency:

In [40]:
word_counts.most_common()

[('the', 3),
 ('night', 3),
 ('was', 3),
 ('dark', 1),
 ('and', 1),
 ('quiet.', 1),
 ('cold.', 1),
 ('very', 1),
 ('dark.', 1)]

Or we can ask for only the five most frequent:

In [41]:
word_counts.most_common(5)

[('the', 3), ('night', 3), ('was', 3), ('dark', 1), ('and', 1)]

his gives us our first basic frequency analysis.

**But There Is a Problem...**

Look carefully at the results.

Why does Python treat `dark` and `dark.` as two different words?

Our `.split()` method only separated the string at spaces. It did not understand that the period in "dark." is punctuation rather than part of the word.

This introduces an important issue in text analysis: before counting words, we often need to **preprocess our text.**

For now, we can remove some punctuation using .replace():

In [46]:
clean_text = text.lower().replace(".", "").replace(",", "")
print(clean_text)

the night was dark and quiet
the night was cold
the night was very dark

Then split and count again:

In [44]:
words = clean_text.split()

word_counts = Counter(words)

word_counts.most_common()

[('the', 3),
 ('night', 3),
 ('was', 3),
 ('dark', 2),
 ('and', 1),
 ('quiet', 1),
 ('cold', 1),
 ('very', 1)]

Now `"dark"` and `"dark."` are counted as the same word.

**Try It Yourself**

Create a variable containing a short paragraph of your choice. Then:

* Convert the text to lowercase.
* Remove periods and commas.
* Split the text into a list of words.
* Use Counter to count the words.
*  Use `.most_common(5)` to identify the five most frequent words.

What are the most frequent words? Are they the words you would consider most meaningful or important in the passage?

###7. Working with Larger Collections of Text

So far, we have worked with a single string:

`text = "The night was dark and quiet."`

But most text analysis projects involve collections of texts.

For example, we might want to compare:

* novels written by different authors
* poems from different time periods
* reviews with different ratings
* interviews with different speakers
* student papers from different disciplines

When working with larger collections, we need a way to organize both our texts and information about those texts.

One of the most common ways to do this in Python is with a **DataFrame**.

A **DataFrame** organizes data into rows and columns, much like a spreadsheet.

To work with **DataFrames**, we will use a Python package called `pandas`.

First, import pandas:

In [52]:
import pandas as pd

Now we can create a small dataset that lists author names, book titles, and years of publication as three lists:

In [55]:
authors = ["Jane Austen", "Mary Shelley", "Charles Dickens"]

titles = ["Pride and Prejudice", "Frankenstein", "Great Expectations"]

years = [1813, 1818, 1861]

We can combine these lists into a DataFrame, a table made up of rows and columns.

In [56]:
df = pd.DataFrame(
    list(zip(authors, titles, years)),
    columns=["author", "title", "year"]
)

df

            author                title  year
0      Jane Austen  Pride and Prejudice  1813
1     Mary Shelley         Frankenstein  1818
2  Charles Dickens   Great Expectations  1861

When working with larger datasets, we usually won't enter all of our data manually. Instead, we can load an existing dataset.

One common format is a **CSV (comma-separated values)** file. CSV files store tabular data and can also be opened in programs such as Excel or Google Sheets.

We can upload a CSV to Google Colab and then turn it into a DataFrame :

In [ ]:
from google.colab import files

uploaded = files.upload()

In [ ]:
df = pd.read_csv("[uploaded_csv_name].csv")

#### Exploring a Dataframe

When working with a new dataset, one of the first things we want to do is inspect it.

In [57]:
df

            author                title  year
0      Jane Austen  Pride and Prejudice  1813
1     Mary Shelley         Frankenstein  1818
2  Charles Dickens   Great Expectations  1861

View the first few rows:

In [58]:
df.head()

            author                title  year
0      Jane Austen  Pride and Prejudice  1813
1     Mary Shelley         Frankenstein  1818
2  Charles Dickens   Great Expectations  1861

Check its dimensions:

In [59]:
df.shape

(3, 3)

The output means that our DataFrame contains 3 rows and 3 columns.

View the column names:

In [60]:
df.columns

Index(['author', 'title', 'year'], dtype='object')

#### Selecting a Column

We can select a particular column using square brackets:

In [61]:
df["author"]

0        Jane Austen
1       Mary Shelley
2    Charles Dickens
Name: author, dtype: object

This becomes particularly useful when one of our columns contains the actual text that we want to analyze.

#### Text and Metadata

Let's create a DataFrame that looks more like a small corpus:

In [63]:
data = {
    "author": ["Author A", "Author B", "Author C", "Author D"],
    "genre": ["fiction", "fiction", "poetry", "poetry"],
    "year": [1850, 1875, 1820, 1890],
    "text": [
        "The night was dark and quiet.",
        "The morning was bright and warm.",
        "The moon appeared over the dark sea.",
        "The sea was quiet beneath the moon."
    ]
}

df = pd.DataFrame(data)

df

     author    genre  year                                  text
0  Author A  fiction  1850         The night was dark and quiet.
1  Author B  fiction  1875      The morning was bright and warm.
2  Author C   poetry  1820  The moon appeared over the dark sea.
3  Author D   poetry  1890   The sea was quiet beneath the moon.

Here we have two broad kinds of information.

**Textual data** contains the language we want to analyze:

`text`

**Metadata** describes the texts:

`author, genre, year`

Metadata is especially important in corpus analysis because it allows us to compare groups of texts.

Earlier, we applied methods to a single string using `text.lower()`

We can also perform string operations on an entire column of textual data.

For example:

In [64]:
df["text"].str.lower()

0           the night was dark and quiet.
1        the morning was bright and warm.
2    the moon appeared over the dark sea.
3     the sea was quiet beneath the moon.
Name: text, dtype: object

Notice the addition of `.str. `in this operation.

Because df["text"] contains many strings, .str tells pandas that we want to perform a string operation on each item in the column.

We can save the results in a new column:

In [65]:

df["text_lower"] = df["text"].str.lower()

df

,author,genre,year,text,text_lower
0,Author A,fiction,1850,The night was dark and quiet.,the night was dark and quiet.
1,Author B,fiction,1875,The morning was bright and warm.,the morning was bright and warm.
2,Author C,poetry,1820,The moon appeared over the dark sea.,the moon appeared over the dark sea.
3,Author D,poetry,1890,The sea was quiet beneath the moon.,the sea was quiet beneath the moon.

#### Creating New Measurements

We can also calculate information about each text.

For example, count the number of characters:

In [66]:
df["character_count"] = df["text"].str.len()

df

,author,genre,year,text,text_lower,character_count
0,Author A,fiction,1850,The night was dark and quiet.,the night was dark and quiet.,29
1,Author B,fiction,1875,The morning was bright and warm.,the morning was bright and warm.,32
2,Author C,poetry,1820,The moon appeared over the dark sea.,the moon appeared over the dark sea.,36
3,Author D,poetry,1890,The sea was quiet beneath the moon.,the sea was quiet beneath the moon.,35

Or count the number of words:

In [67]:
df["word_count"] = df["text"].str.split().str.len()

df

,author,genre,year,text,text_lower,character_count,word_count
0,Author A,fiction,1850,The night was dark and quiet.,the night was dark and quiet.,29,6
1,Author B,fiction,1875,The morning was bright and warm.,the morning was bright and warm.,32,6
2,Author C,poetry,1820,The moon appeared over the dark sea.,the moon appeared over the dark sea.,36,7
3,Author D,poetry,1890,The sea was quiet beneath the moon.,the sea was quiet beneath the moon.,35,7

#### Sorting Data

Once we've created measurements, we can sort our texts according to them. For example, we can sort by word count. Default sort is from smallest to largest; reverse by setting `ascending` to False.

In [68]:
df.sort_values("word_count")

,author,genre,year,text,text_lower,character_count,word_count
0,Author A,fiction,1850,The night was dark and quiet.,the night was dark and quiet.,29,6
1,Author B,fiction,1875,The morning was bright and warm.,the morning was bright and warm.,32,6
2,Author C,poetry,1820,The moon appeared over the dark sea.,the moon appeared over the dark sea.,36,7
3,Author D,poetry,1890,The sea was quiet beneath the moon.,the sea was quiet beneath the moon.,35,7

In [69]:
df.sort_values("word_count", ascending=False)

,author,genre,year,text,text_lower,character_count,word_count
3,Author D,poetry,1890,The sea was quiet beneath the moon.,the sea was quiet beneath the moon.,35,7
2,Author C,poetry,1820,The moon appeared over the dark sea.,the moon appeared over the dark sea.,36,7
1,Author B,fiction,1875,The morning was bright and warm.,the morning was bright and warm.,32,6
0,Author A,fiction,1850,The night was dark and quiet.,the night was dark and quiet.,29,6

You could ask them:

Which text in our dataset contains the most words?

This is simple, but it's getting them accustomed to the idea that rows are observations and columns are variables/features.

#### Filtering Data

Metadata allows us to select only certain texts.

For example, suppose we only want fiction:

In [70]:
df[df["genre"] == "fiction"]

,author,genre,year,text,text_lower,character_count,word_count
0,Author A,fiction,1850,The night was dark and quiet.,the night was dark and quiet.,29,6
1,Author B,fiction,1875,The morning was bright and warm.,the morning was bright and warm.,32,6

We can also filter numerical information:

In [71]:
df[df["year"] > 1850]

,author,genre,year,text,text_lower,character_count,word_count
1,Author B,fiction,1875,The morning was bright and warm.,the morning was bright and warm.,32,6
3,Author D,poetry,1890,The sea was quiet beneath the moon.,the sea was quiet beneath the moon.,35,7

This is one of the major reasons metadata matters. We can define a subset of our corpus based on the research question we're asking.

#### Comparing Groups

We can also group texts according to their metadata.

For example:

In [72]:
df.groupby("genre")["word_count"].mean()

genre
fiction    6.0
poetry     7.0
Name: word_count, dtype: float64

This asks Python to:

1. Group the texts according to genre.
2. Look at word_count.
3. Calculate the average for each group.

Obviously our example dataset is much too small to draw meaningful conclusions...but imagine that df contained 10,000 poems.

## From Python Basics to Your Corpus

You will eventually use Python to construct, explore, and analyze a corpus for your own research project. Your corpus may contain dozens, hundreds, or thousands of texts, but the basic structures we practiced in this tutorial will remain the same.

As you begin thinking about your own corpus, consider how you might represent it as a **DataFrame**, with each row representing a unit of analysis and each column containing textual data, metadata, or a measurement derived from the text.

Consider:

1. **What will one row represent?**  
   Will each row contain a novel, poem, article, chapter, speech, review, interview, or another unit of analysis?

2. **What will your text column contain?**  
   Will you analyze complete texts, excerpts, paragraphs, sentences, or another unit of language?

3. **What metadata will you need?**  
   What information will allow you to identify, organize, filter, and compare your texts? This might include author, title, date, genre, publication venue, literary period, or another category relevant to your research question.

4. **What might you want Python to measure?**  
   Think about the operations we practiced in this tutorial. What could you count or calculate across your corpus? Later, we will expand beyond simple word and character counts to more sophisticated forms of text analysis.

5. **What comparisons might your metadata make possible?**  
   Could you compare authors, genres, time periods, publications, or other groups? Which comparisons would help you investigate your research question?

6. **What will require interpretation?**  
   Python can quickly count, sort, filter, and compare data, but those results do not explain themselves. What kinds of contextual or literary knowledge would you need to interpret the patterns you find?


## Additional Python and Text Analysis Resources

The following resources provide additional introductions to Python and text analysis:
- [Kaggle Learn: Python](https://www.kaggle.com/learn/python) — A short, hands-on introduction to Python using interactive notebooks. Kaggle also offers a free [Pandas course](https://www.kaggle.com/learn/pandas) for additional practice working with DataFrames.

- [Introduction to Cultural Analytics & Python](https://melaniewalsh.github.io/Intro-Cultural-Analytics/) — A free online textbook by Melanie Walsh designed specifically for humanities and cultural researchers. Covers Python fundamentals, pandas, text analysis, visualization, and working with cultural data.

- [The Programming Historian: Python Tutorials](https://programminghistorian.org/en/lessons/?topic=python) — Peer-reviewed, step-by-step tutorials for using Python in humanities research, including text analysis, data collection, and working with digital archives.

- [W3Schools: Python Tutorial](https://www.w3schools.com/python/) — Short explanations and runnable examples covering Python fundamentals. Particularly useful as a quick reference when you forget how a particular command or piece of syntax works.

- [Python for Everybody](https://www.py4e.com/) — Free course materials, lectures, exercises, and a textbook by Charles Severance for learning Python from the beginning.

- [spaCy 101](https://spacy.io/usage/spacy-101) — Free documentation and tutorials for the spaCy natural language processing library. This will become particularly useful as we move into tokenization, part-of-speech tagging, lemmatization, and named entity recognition later in the course.